# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tochandhkedahd',
            name='routepic',
            field=models.ImageField(default='images/Integrated Route Map-pagep001_6.jpg', height_field=550, upload_to='', width_field=350),
        ),
        migrations.AddField(
            model_name='tochandhkedawd',
            name='routepic',
            field=models.ImageField(default='images/Integrated Route Map-pagep001_6.jpg', height_field=550, upload_to='', width_field=350),
        ),
        migrations.AddField(
            model_name='topalajhd',
            name='routepic',
            field=models.ImageField(default='images/Integrated Route Map-pagep001_6.jpg', height_field=550, upload_to='', width_field=350),
        ),
        migrations.AddField(
            model_name='topalajwd',
            name='routepic',
            field=models.ImageField(default='images/Integrated Route Map-pagep001_6.jpg', height_field=550, upload_to='', width_field=350),
        ),
    ]
