# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleservice', '0002_auto_20170318_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tochandhkedahd',
            name='routepic',
            field=models.ImageField(default='images/Integrated Route Map-pagep001_6.jpg', upload_to=''),
        ),
    ]
