# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttleservice', '0003_auto_20170318_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tochandhkedawd',
            name='routepic',
            field=models.ImageField(default='images/Integrated Route Map-pagep001_6.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='topalajhd',
            name='routepic',
            field=models.ImageField(default='images/Integrated Route Map-pagep001_6.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='topalajwd',
            name='routepic',
            field=models.ImageField(default='images/Integrated Route Map-pagep001_6.jpg', upload_to=''),
        ),
    ]
