# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_retypepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ReTypePassword',
            field=models.CharField(max_length=150),
        ),
    ]
