# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170319_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ReTypePassword',
        ),
    ]
