# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_userprofile_retypepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_reg',
            field=models.BooleanField(default=False),
        ),
    ]
