# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terashare', '0007_auto_20170311_1500'),
        ('profiles', '0006_userprofile_course_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terashare.Course')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile')),
            ],
        ),
    ]
