# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0008_coursetimings_days'),
        ('timetable', '0004_auto_20170320_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesreg',
            name='course10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course10', to='terashare.Course'),
        ),
        migrations.AddField(
            model_name='coursesreg',
            name='course11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course11', to='terashare.Course'),
        ),
        migrations.AddField(
            model_name='coursesreg',
            name='course12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course12', to='terashare.Course'),
        ),
        migrations.AddField(
            model_name='coursesreg',
            name='course3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course3', to='terashare.Course'),
        ),
        migrations.AddField(
            model_name='coursesreg',
            name='course4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course4', to='terashare.Course'),
        ),
        migrations.AddField(
            model_name='coursesreg',
            name='course5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course5', to='terashare.Course'),
        ),
        migrations.AddField(
            model_name='coursesreg',
            name='course6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course6', to='terashare.Course'),
        ),
        migrations.AddField(
            model_name='coursesreg',
            name='course7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course7', to='terashare.Course'),
        ),
        migrations.AddField(
            model_name='coursesreg',
            name='course8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course8', to='terashare.Course'),
        ),
        migrations.AddField(
            model_name='coursesreg',
            name='course9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course9', to='terashare.Course'),
        ),
    ]
