# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 22, 19, 6, 54, 939370)),
        ),
    ]
