# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=6)),
                ('course_code', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Stream', models.CharField(choices=[('Btech', 'Btech'), ('Mtech', 'Mtech'), ('Msc', 'Msc'), ('Ma', 'Ma'), ('Phd', 'Phd'), ('Alumni', 'Alumni')], default='Btech', max_length=5)),
                ('file', models.FileField(upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terashare.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terashare.Folder'),
        ),
    ]
