# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Stream',
            field=models.CharField(choices=[('Btech', 'Btech'), ('Mtech', 'Mtech'), ('Msc', 'Msc'), ('Ma', 'Ma'), ('Phd', 'Phd'), ('Alumni', 'Alumni')], max_length=5),
        ),
    ]
