# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0002_auto_20170308_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='Stream',
        ),
    ]
