# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0005_auto_20170311_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='terashare.Folder'),
        ),
    ]
