# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0006_auto_20170311_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Stream',
            field=models.CharField(default='Stream', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='Title',
            field=models.CharField(default='Title', max_length=150),
        ),
    ]
