# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0010_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseTimings',
        ),
    ]
