# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0012_coursetimings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=6)),
                ('course_code', models.CharField(max_length=3, null=True)),
                ('Sunday', models.BooleanField()),
                ('Monday', models.BooleanField()),
                ('Tuesday', models.BooleanField()),
                ('Wednesday', models.BooleanField()),
                ('Thursday', models.BooleanField()),
                ('Friday', models.BooleanField()),
                ('Saturday', models.BooleanField()),
                ('From', models.TimeField()),
                ('To', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='coursetimings',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseTimings',
        ),
    ]
