# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0013_auto_20170321_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kourse',
        ),
        migrations.AddField(
            model_name='course',
            name='Friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='From',
            field=models.TimeField(default=datetime.datetime(2017, 3, 21, 16, 5, 27, 331541)),
        ),
        migrations.AddField(
            model_name='course',
            name='Monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='Saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='Sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='Thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='To',
            field=models.TimeField(default=datetime.datetime(2017, 3, 21, 16, 5, 27, 331541)),
        ),
        migrations.AddField(
            model_name='course',
            name='Tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='Wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
