# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0014_auto_20170321_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='From',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='To',
            field=models.TimeField(),
        ),
    ]
