# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0015_auto_20170321_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Friday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Monday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Saturday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Sunday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Thursday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Tuesday',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Wednesday',
            field=models.BooleanField(),
        ),
    ]
