# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0016_auto_20170321_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
