# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0017_delete_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terashare.Course'),
        ),
        migrations.AlterField(
            model_name='file',
            name='Stream',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='Title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='file',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terashare.Folder'),
        ),
    ]
