# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0018_auto_20170321_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
