# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0020_auto_20170322_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
