# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0022_remove_file_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='report',
            field=models.BooleanField(default=False),
        ),
    ]
