# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terashare', '0024_auto_20170322_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Friday',
            new_name='Fri',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Monday',
            new_name='Mon',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Saturday',
            new_name='Sat',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Thursday',
            new_name='Thu',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Tuesday',
            new_name='Tue',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Wednesday',
            new_name='Wed',
        ),
    ]
