# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccomodationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name1', models.CharField(max_length=100)),
                ('Gender1', models.CharField(max_length=10)),
                ('Name2', models.CharField(max_length=100)),
                ('Gender2', models.CharField(max_length=10)),
                ('Name3', models.CharField(max_length=100)),
                ('Gender3', models.CharField(max_length=10)),
                ('Datefrom', models.DateField()),
                ('Dateto', models.DateField()),
                ('Purpose', models.CharField(max_length=500)),
            ],
        ),
    ]
