# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mess', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('day', models.CharField(choices=[('Su', 'Sunday'), ('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday')], max_length=50)),
                ('mess', models.CharField(choices=[('Mohini(Lower)', 'Mohini'), ('Jaiswal(Upper)', 'Jaiswal')], max_length=50)),
                ('session', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], max_length=50)),
            ],
        ),
    ]
