# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Image', models.ImageField(default='\\static\\lostfound\\images\\empty.png', upload_to='')),
                ('Description', models.TextField(max_length=500)),
                ('Found_on', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Image', models.ImageField(default='\\static\\lostfound\\images\\empty.png', upload_to='')),
                ('Description', models.TextField(max_length=500)),
                ('Last_Seen', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
